version: '3.8'
services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn start:dev'
    depends_on:
      - postgres-teddy-open-finance
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - node-tech-net

  postgres-teddy-open-finance:
    image: postgres:latest
    container_name: postgres-teddy-open-finance
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - node-tech-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  node-tech-net:

volumes:
  postgres-data:

